branches:
  only:
    - master

language: python

services:
  - mongodb

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6-beta

matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.4

install:
  - pip install https://github.com/django-nonrel/django/tarball/nonrel-$DJANGO_VERSION
  - pip install https://github.com/django-nonrel/django-dbindexer/tarball/master
  - pip install https://github.com/django-nonrel/djangotoolbox/tarball/master
  - python setup.py install

script: cd tests && python runtests.py
